INSERT INTO eis_t.EIS_BTCHGRPLOG
(
SELECT 
C.RqstSID AS RQSTSID,
C.REQUEST_ID AS RQSTID,
'R' AS RQSTLOADSTATCD,
C.ETL_BtchGrpCd AS ETL_BtchGrpCd,
C.TOTAL_DELTAS AS TOTDLTACNT,
NULL AS THNDLTACNT,
NULL AS APLDDLTACNT, 
NULL AS INSERTBY,
NULL AS INSERTDT
FROM
	(
	SELECT 
	A.RqstSID,
	A.REQUEST_ID,
	A.ETL_BtchGrpCd, 
	A.TOTAL_DELTAS
	FROM 
		(
		SELECT 
		X.RqstSID,
		X.REQUEST_ID,
		X.ETL_BtchGrpCd, 
		COUNT(X.RqstSID) TOTAL_DELTAS
		FROM
			eis_stg_t.VTTP_D_xi X 
		WHERE 
			AUDITFK IN 
				(
				SELECT ETL_TABLE_AUDIT_PK FROM eis_t.A_ETL_TABLE_AUDIT WHERE TABLE_NAME = 'VTTP_D_xi' AND TBL_ETL_STATUS = 'In Progress'
				)
				GROUP BY  
				X.RqstSID,X.REQUEST_ID, X.ETL_BtchGrpCd
		) A 
		INNER JOIN 
			eis_t.EIS_REQUEST_LOG B 
			ON 
			A.RqstSID = B.RqstSID AND 
			B.RQSTLoadStatCd = 'R'
	) C
); 



