COPY INTO @{{DATABASE}}.{{SCHEMA_STG}}.STG_TBL_STG/{{TABLE_NAME}}_reqlog_all.txt FROM (SELECT RQSTID FROM {{DATABASE}}.{{SCHEMA_T}}.EIS_REQUEST_LOG WHERE PSA_NAME LIKE {{PSANAME}} AND LOG_SYSTEM = {{SRCSYS}})
FILE_FORMAT = (TYPE = CSV, compression = NONE) SINGLE = TRUE OVERWRITE = TRUE; GET @{{DATABASE}}.{{SCHEMA_STG}}.STG_TBL_STG/{{TABLE_NAME}}_reqlog_all.txt file://{{INTERMEDIATE_FILE_PATH}};
