INSERT INTO {{SCHEMA_STG_T}}.{{PARAMTGTTABLE}}
(
     ABLAD,
     ABRVW,
     AEDAT,
     AKMNG,
     AKTNR,
     ANZLIPOS,
     AUDAT,
     AUDITFK,
     AUFNR,
     AUGRU,
     BDART,
     BEROT,
     BLDAT,
     BOLNR,
     BRGEW,
     BSARK,
     BSTNK,
     BUKRS,
     BWAPPLNM,
     BWART,
     BWVORG,
     BZIRK,
     CHARG,
     DATAPAKID,
     EAN11,
     ERDAT,
     ERNAM,
     ERZET,
     ETL_BtchGrpCd,
     EXPKZ,
     FAKSK,
     FAKSP,
     FKREL,
     GEWEI,
     GRKOR,
     GSBER,
     INCO1,
     INCO2,
     J_3ACADA,
     J_3ADEPM,
     J_3AETENR,
     J_3AKVGR10,
     J_3AKVGR6,
     J_3AKVGR8,
     J_3AKVGR9,
     J_3ALNGR,
     J_3APGNR,
     J_3ARQDA,
     J_3ASIZE,
     J_3AVDAT,
     J_4KRCAT,
     J_4KSCAT,
     KCBRGEW,
     KCGEWEI,
     KCMENG,
     KCNTGEW,
     KCVOLEH,
     KCVOLUM,
     KDGRP,
     KMEIN,
     KNTTP,
     KOMKZ,
     KOQUA,
     KOSTA,
     KPEIN,
     KUNAG,
     KUNNR,
     KVGR1,
     KVGR2,
     KVGR3,
     KVGR4,
     KVGR5,
     KZBEW,
     KZTLF,
     KZVBR,
     KZWI1,
     KZWI2,
     KZWI3,
     KZWI4,
     KZWI5,
     KZWI6,
     LADGR,
     LFART,
     LFDAT,
     LFIMG,
     LGMNG,
     LGNUM,
     LGORT,
     LGPLA,
     LGTYP,
     LIFEX,
     LIFNR,
     LIFSK,
     LPRIO,
     LSTEL,
     MATKL,
     MATNR,
     MATWA,
     MBDAT,
     MEINS,
     MTART,
     MTVFP,
     MVGR1,
     MVGR2,
     MVGR3,
     MVGR4,
     MVGR5,
     NETWR,
     NTGEW,
     PARTNO,
     PERIV,
     PKUNRE,
     PKUNRG,
     PLART,
     POSAR,
     POSNR,
     PRCTR,
     PRODH,
     PS_POSID,
     PSPDNR,
     PSTYV ,
     PVRTNR,
     RECORD,
     Record_Checksum,
     REQUEST_ID,
     ROCANCEL,
     ROUTE,
     RowEffStrtTmstmp,
     SHKZG,
     RQSTSID,
     SPARA,
     STADAT,
     TDDAT,
     TRAGR,
     TRAID,
     TRATY,
     UECHA,
     UMVKN,
     UMVKZ,
     UVVLK,
     VBEAF,
     VBEAV,
     VBELN,
     VBTYP,
     VDATU,
     VERUR,
     VGBEL,
     VGPOS,
     VGREF,
     VGTYP,
     VKBUR,
     VKGRP,
     VKORG,
     VOLEH,
     VOLUM,
     VRKME,
     VSBED,
     VSTEL,
     VTWEG,
     WA_DELAY_LF,
     WADAT,
     WADAT_IST,
     WAERK,
     WBSTA,
     WERKS,
     XABLN,
     ZZ_ANZPK,
     ZZ_BUS_ORG,
     ZZ_CAT_CD,
     ZZAUART,
     ZZFULL_CASE_UNIT,
     ZZREPK_UNIT,
     ZZVASIND,
     ZZ_GNDRAGE,
     ZZ_IDP_DT,
     ZZ_IDP_FL,
     ZZ_J_3AVASG,
     ZZ_KDKG5,
     ZZ_LEDAT,
     ZZ_NETPR,
     ZZ_PLN_SCHED_DT,
     ZZ_SCHED_LSTDT,
     ZZ_SORD_QTR,
     ZZ_TYP_GRP,
     ZZ_SEGMENT,
     ZZ_SUB_CAT
)
SELECT 
     ABLAD as ABLAD,
     ABRVW as ABRVW,
     AEDAT as AEDAT,
     AKMNG as AKMNG,
     AKTNR as AKTNR,
     ANZLIPOS as ANZLIPOS,
     AUDAT as AUDAT,
     D.ETL_TABLE_AUDIT_PK as AUDITFK,
     AUFNR as AUFNR,
     AUGRU as AUGRU,
     BDART as BDART,
     BEROT as BEROT,
     BLDAT as BLDAT,
     BOLNR as BOLNR,
     BRGEW as BRGEW,
     BSARK as BSARK,
     BSTNK as BSTNK,
     BUKRS as BUKRS,
     BWAPPLNM as BWAPPLNM,
     BWART as BWART,
     TO_DECIMAL(BWVORG) as BWVORG,
     BZIRK as BZIRK,
     CHARG as CHARG,
     TO_DECIMAL(DATAPAKID) as DATAPAKID,
     EAN11 as EAN11,
     ERDAT as ERDAT,
     ERNAM as ERNAM,
     ERZET as ERZET,
     CASE WHEN BG.BATCH_GROUP <>'ASIA' 
	      THEN B.RgnNm 
		  ELSE 'ASIA' 
	 END as ETL_BtchGrpCd,
     EXPKZ as EXPKZ,
     FAKSK as FAKSK,
     FAKSP as FAKSP,
     FKREL as FKREL,
     GEWEI as GEWEI,
     TO_DECIMAL(GRKOR) as GRKOR,
     GSBER as GSBER,
     INCO1 as INCO1,
     INCO2 as INCO2,
     J_3ACADA as J_3ACADA,
     J_3ADEPM as J_3ADEPM,
     TO_DECIMAL(J_3AETENR) as J_3AETENR,
     J_3AKVGR10 as J_3AKVGR10,
     J_3AKVGR6 as J_3AKVGR6,
     J_3AKVGR8 as J_3AKVGR8,
     J_3AKVGR9 as J_3AKVGR9,
     TO_DECIMAL(J_3ALNGR) as J_3ALNGR,
     J_3APGNR as J_3APGNR,
     J_3ARQDA as J_3ARQDA,
     J_3ASIZE as J_3ASIZE,
     J_3AVDAT as J_3AVDAT,
     J_4KRCAT as J_4KRCAT,
     J_4KSCAT as J_4KSCAT,
     KCBRGEW as KCBRGEW,
     KCGEWEI as KCGEWEI,
     KCMENG as KCMENG,
     KCNTGEW as KCNTGEW,
     KCVOLEH as KCVOLEH,
     KCVOLUM as KCVOLUM,
     KDGRP as KDGRP,
     KMEIN as KMEIN,
     KNTTP as KNTTP,
     KOMKZ as KOMKZ,
     KOQUA as KOQUA,
     KOSTA as KOSTA,
     KPEIN as KPEIN,
     KUNAG as KUNAG,
     KUNNR as KUNNR,
     KVGR1 as KVGR1,
     KVGR2 as KVGR2,
     KVGR3 as KVGR3,
     KVGR4 as KVGR4,
     KVGR5 as KVGR5,
     KZBEW as KZBEW,
     KZTLF as KZTLF,
     KZVBR as KZVBR,
     KZWI1 as KZWI1,
     KZWI2 as KZWI2,
     KZWI3 as KZWI3,
     KZWI4 as KZWI4,
     KZWI5 as KZWI5,
     KZWI6 as KZWI6,
     LADGR as LADGR,
     LFART as LFART,
     LFDAT as LFDAT,
     LFIMG as LFIMG,
     LGMNG as LGMNG,
     LGNUM as LGNUM,
     LGORT as LGORT,
     LGPLA as LGPLA,
     LGTYP as LGTYP,
     LIFEX as LIFEX,
     LIFNR as LIFNR,
     LIFSK as LIFSK,
     TO_DECIMAL(LPRIO) as LPRIO,
     LSTEL as LSTEL,
     MATKL as MATKL,
     MATNR as MATNR,
     MATWA as MATWA,
     MBDAT as MBDAT,
     MEINS as MEINS,
     MTART as MTART,
     MTVFP as MTVFP,
     MVGR1 as MVGR1,
     MVGR2 as MVGR2,
     MVGR3 as MVGR3,
     MVGR4 as MVGR4,
     MVGR5 as MVGR5,
     NETWR as NETWR,
     NTGEW as NTGEW,
     TO_NUMBER(PARTNO) as PARTNO,
     PERIV as PERIV,
     PKUNRE as PKUNRE,
     PKUNRG as PKUNRG,
     PLART as PLART,
     POSAR as POSAR,
     TO_DECIMAL(POSNR) as POSNR,
     PRCTR as PRCTR,
     PRODH as PRODH,
     PS_POSID as PS_POSID,
     PSPDNR as PSPDNR,
     PSTYV as PSTYV,
     TO_DECIMAL(PVRTNR) as PVRTNR,
     TO_NUMBER(RECORD) as RECORD,
     'Not Used' as Record_Checksum,
     REQUEST as REQUEST_ID,
     ROCANCEL as ROCANCEL,
     ROUTE as ROUTE,
     TO_TIMESTAMP_NTZ(CURRENT_TIMESTAMP(0)) as RowEffStrtTmstmp,
     SHKZG as SHKZG,
     TO_NUMBER(SID) as SID,
     SPARA as SPARA,
     STADAT as STADAT,
     TDDAT as TDDAT,
     TRAGR as TRAGR,
     TRAID as TRAID,
     TRATY as TRATY,
     TO_DECIMAL(UECHA) as UECHA,
     UMVKN as UMVKN,
     UMVKZ as UMVKZ,
     UVVLK as UVVLK,
     VBEAF as VBEAF,
     VBEAV as VBEAV,
     VBELN as VBELN,
     VBTYP as VBTYP,
     VDATU as VDATU,
     VERUR as VERUR,
     VGBEL as VGBEL,
     TO_DECIMAL(VGPOS) as VGPOS,
     VGREF as VGREF,
     VGTYP as VGTYP,
     VKBUR as VKBUR,
     VKGRP as VKGRP,
     VKORG as VKORG,
     VOLEH as VOLEH,
     VOLUM as VOLUM,
     VRKME as VRKME,
     VSBED as VSBED,
     VSTEL as VSTEL,
     VTWEG as VTWEG,
     WA_DELAY_LF as WA_DELAY_LF,
     WADAT as WADAT,
     WADAT_IST as WADAT_IST,
     WAERK as WAERK,
     WBSTA as WBSTA,
     WERKS as WERKS,
     XABLN as XABLN,
     TO_DECIMAL(ZZ_ANZPK) as ZZ_ANZPK,
     TO_DECIMAL(ZZ_BUS_ORG) as ZZ_BUS_ORG,
     TO_DECIMAL(ZZ_CAT_CD) as ZZ_CAT_CD,
     ZZAUART as ZZAUART,
     ZZFULL_CASE_UNIT as ZZFULL_CASE_UNIT,
     ZZREPK_UNIT as ZZREPK_UNIT,
     ZZVASIND as ZZVASIND,
     ZZ_GNDRAGE as ZZ_GNDRAGE,
     ZZ_IDP_DT as ZZ_IDP_DT,
     ZZ_IDP_FL as ZZ_IDP_FL,
     ZZ_J_3AVASG as ZZ_J_3AVASG,
     ZZ_KDKG5 as ZZ_KDKG5,
     ZZ_LEDAT as ZZ_LEDAT,
     ZZ_NETPR as ZZ_NETPR,
     ZZ_PLN_SCHED_DT as ZZ_PLN_SCHED_DT,
     ZZ_SCHED_LSTDT as ZZ_SCHED_LSTDT,
     ZZ_SORD_QTR as ZZ_SORD_QTR,
     ZZ_TYP_GRP as ZZ_TYP_GRP,
     TO_DECIMAL(ZZ_SEGMENT) as ZZ_SEGMENT,
     TO_DECIMAL(ZZ_SUB_CAT) as ZZ_SUB_CAT
FROM 
    {{SCHEMA_STG}}.{{PARAMSRCTABLE}} A
LEFT OUTER JOIN
   (SELECT R.RGNNM as RgnNm,C.CmpyCd as RgnCd
    FROM 
	    {{SCHEMA_T}}.CmpyToRgnConfig C,
		{{SCHEMA_T}}.RgnERP R
    WHERE C.RGNCD=R.RGNCD GROUP BY C.CmpyCd,R.RgnNm) B
on RPAD(A.BUKRS,5)=B.RgnCd
LEFT OUTER JOIN
	(SELECT ETL_TABLE_AUDIT_PK FROM {{SCHEMA_T}}.A_ETL_TABLE_AUDIT WHERE table_name='{{PARAMTGTTABLE}}' AND TBL_ETL_STATUS='In Progress') D
	ON 1=1
LEFT OUTER JOIN 
     (SELECT {{BATCH_GROUP}} AS BATCH_GROUP) BG
ON 1=1;